export PROJECT =kai-cyber-home-assessment
IMPORT_PATH := github.com/hamza-sharif/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
	-v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
    --link idP-db:idP-db \
    ${DEV_IMAGE}
